CC = gcc

PROGRAMS = p137 p139 p143 p145 p147 p148 p149

all: $(PROGRAMS)

p137: p137.c
	$(CC) -Wall -o $@ $^

p139: p139.c
	$(CC) -Wall -o $@ $^

p143: p143.c
	$(CC) -Wall -o $@ $^

p145: p145.c
	$(CC) -Wall -o $@ $^

p147: p147.c
	$(CC) -Wall -o $@ $^

p148: p148.c
	$(CC) -Wall -o $@ $^

p149: p149.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
