CC = gcc

PROGRAMS = p116 p117 p119 p121 p123 p125 p126

all: $(PROGRAMS)

p116: p116.c
	$(CC) -Wall -o $@ $^

p117: p117.c
	$(CC) -Wall -o $@ $^

p119: p119.c
	$(CC) -Wall -o $@ $^

p121: p121.c
	$(CC) -Wall -o $@ $^

p123: p123.c
	$(CC) -Wall -o $@ $^

p125: p125.c
	$(CC) -Wall -o $@ $^

p126: p126.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
