CC = gcc

PROGRAMS = array str full length full1 full2 p_array double tri

all: $(PROGRAMS)

array: array.c
	$(CC) -Wall -o $@ $^

str: str.c
	$(CC) -Wall -o $@ $^

full: full.c
	$(CC) -Wall -o $@ $^

length: length.c
	$(CC) -Wall -o $@ $^

full1: full1.c
	$(CC) -Wall -o $@ $^

full2: full2.c
	$(CC) -Wall -o $@ $^

p_array: p_array.c
	$(CC) -Wall -o $@ $^

double: double.c
	$(CC) -Wall -o $@ $^

tri: tri.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
