CC = gcc

PROGRAMS = init2a init2b first max size die sqr sqr-i rec

all: $(PROGRAMS)

init2a: init2a.c
	$(CC) -Wall -o $@ $^

init2b: init2b.c
	$(CC) -Wall -o $@ $^

first: first.c
	$(CC) -Wall -o $@ $^

max: max.c
	$(CC) -Wall -o $@ $^

size: size.c
	$(CC) -Wall -o $@ $^

die: die.c
	$(CC) -Wall -o $@ $^

sqr: sqr.c
	$(CC) -Wall -o $@ $^

sqr-i: sqr-i.c
	$(CC) -Wall -o $@ $^

rec: rec.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
