// Generated by CoffeeScript 1.4.0
(function() {
  var city, forecast, temp, weatherReport, _ref;

  weatherReport = function(location) {
    return [location, 72, "Mostly Sunny"];
  };

  _ref = weatherReport("Berkeley, CA"), city = _ref[0], temp = _ref[1], forecast = _ref[2];

  alert(city);

  alert(temp);

  alert(forecast);

}).call(this);
