// Generated by CoffeeScript 1.4.0
(function() {

  alert((function() {
    try {
      return nonexistent / void 0;
    } catch (error) {
      return "Add the error is ..." + error;
    }
  })());

}).call(this);
