// Generated by CoffeeScript 1.4.0
(function() {
  var eldset, grade;

  grade = function(student) {
    if (student.excellentWork) {
      return "A+";
    } else if (student.ikayStuff) {
      if (student.triendHard) {
        return "B";
      } else {
        return "B-";
      }
    } else {
      return "C";
    }
  };

  eldset = 24 > 21 ? "Liz" : "Ike";

  alert(eldset);

}).call(this);
