// Generated by CoffeeScript 1.4.0
(function() {
  var changeNumbers, inner, outer;

  outer = 1;

  changeNumbers = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumbers();

  alert(inner);

}).call(this);
