// Generated by CoffeeScript 1.4.0
(function() {
  var valume, winner;

  if (ignition === true) {
    launch();
  }

  if (band !== SpinalTap) {
    valume = 10;
  }

  if (answer !== false) {
    letTheWildRumpusBegin();
  }

  if (car.speed < limit) {
    accelerate();
  }

  if (pick === 47 || pick === 92 || pick === 13) {
    winner = true;
  }

  print(inspect("My name is " + this.name));

}).call(this);
