// Generated by CoffeeScript 1.4.0
(function() {
  var cube, fill, square;

  square = function(x) {
    return x * x;
  };

  cube = function(x) {
    return square(x) * x;
  };

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "Filling the " + container + " with " + liquid + "...";
  };

  alert(fill("cup"));

}).call(this);
