CC = gcc

PROGRAMS = two_num_multi return_power gcm_lcm prime tom_money select_mon per_com power_km sam_six jukkum

all: $(PROGRAMS)

two_num_multi: two_num_multi.c
	$(CC) -Wall -o $@ $^

return_power: return_power.c
	$(CC) -Wall -o $@ $^

gcm_lcm: gcm_lcm.c
	$(CC) -Wall -o $@ $^

prime: prime.c
	$(CC) -Wall -o $@ $^

tom_money: tom_money.c
	$(CC) -Wall -o $@ $^

select_mon: select_mon.c
	$(CC) -Wall -o $@ $^

per_com: per_com.c
	$(CC) -Wall -o $@ $^

power_km: power_km.c
	$(CC) -Wall -o $@ $^

sam_six: sam_six.c
	$(CC) -Wall -o $@ $^

jukkum: jukkum.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
