// Generated by CoffeeScript 1.4.0
(function() {
  var times;

  times = function(a, b) {
    if (a == null) {
      a = 1;
    }
    if (b == null) {
      b = 2;
    }
    return a * b;
  };

}).call(this);
