CC = gcc

PROGRAMS = 22-1 22-2 22-3 22-4 22-5 22-6 22-7 22-8 22-9 22-10 22-11
	  ex22-1

all: $(PROGRAMS)

22-1: 22-1.c
	$(CC) -Wall -o $@ $^

ex22-1: ex22-1.c
	$(CC) -Wall -o $@ $^

22-2: 22-2.c
	$(CC) -Wall -o $@ $^

22-3: 22-3.c
	$(CC) -Wall -o $@ $^

22-4: 22-4.c
	$(CC) -Wall -o $@ $^

22-5: 22-5.c
	$(CC) -Wall -o $@ $^

22-6: 22-6.c
	$(CC) -Wall -o $@ $^

22-7: 22-7.c
	$(CC) -Wall -o $@ $^

22-8: 22-8.c
	$(CC) -Wall -o $@ $^

22-9: 22-9.c
	$(CC) -Wall -o $@ $^

22-10: 22-10.c
	$(CC) -Wall -o $@ $^

22-11: 22-11.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
