CC = gcc

PROGRAMS = 25-1 25-2 25-3 25-4 25-5 25-6 25-7 25-8

all:$(PROGRAMS)

25-1: 25-1.c
	$(CC) -Wall -o $@ $^

25-2: 25-2.c
	$(CC) -Wall -o $@ $^

25-3: 25-3.c
	$(CC) -Wall -o $@ $^

25-4: 25-4.c
	$(CC) -Wall -o $@ $^

25-5: 25-5.c
	$(CC) -Wall -o $@ $^

25-6: 25-6.c
	$(CC) -Wall -o $@ $^

25-7: 25-7.c
	$(CC) -Wall -o $@ $^

25-8: 25-8.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
