// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  this.clickHandler = function() {
    return alert("clicked");
  };

  element.addEventListener("click", function(e) {
    return _this.clickHandler(e);
  });

}).call(this);
