CC = gcc

PROGRAMS = que18-1 que18-2-1 que18-2-2 que18-2-3

all: $(PROGRAMS)

que18-1: que18-1.c
	$(CC) -Wall -o $@ $^

que18-2-1: que18-2-1.c
	$(CC) -Wall -o $@ $^

que18-2-2: que18-2-2.c
	$(CC) -Wall -o $@ $^

que18-2-3: que18-2-3.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
