CC = gcc

PROGRAMS = 27-01 27-02 27-03 27-04 27-05 27-06 27-07 27-08 27-09 27-10

all: $(PROGRAMS)

27-01: 27-01.c
	$(CC) -Wall -o $@ $^

27-02: 27-02.c
	$(CC) -Wall -o $@ $^

27-03: 27-03.c
	$(CC) -Wall -o $@ $^

27-04: 27-04.c
	$(CC) -Wall -o $@ $^

27-05: 27-05.c
	$(CC) -Wall -o $@ $^

27-06: 27-06.c
	$(CC) -Wall -o $@ $^

27-07: 27-07.c
	$(CC) -Wall -o $@ $^

27-08: 27-08.c
	$(CC) -Wall -o $@ $^

27-09: 27-09.c
	$(CC) -Wall -o $@ $^

27-10: 27-10.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
