CC = gcc

PROGRAMS = p87 p89 p91 p93 p95 p97 p99 p101 p105 p106 p106_2 p107

all: $(PROGRAMS)

p87: p87.c
	$(CC) -Wall -o $@ $^

p89: p89.c
	$(CC) -Wall -o $@ $^

p91: p91.c
	$(CC) -Wall -o $@ $^

p93: p93.c
	$(CC) -Wall -o $@ $^

p95: p95.c
	$(CC) -Wall -o $@ $^

p97: p97.c
	$(CC) -Wall -o $@ $^

p99: p99.c
	$(CC) -Wall -o $@ $^

p101: p101.c
	$(CC) -Wall -o $@ $^

p105: p105.c
	$(CC) -Wall -o $@ $^

p106: p106.c
	$(CC) -Wall -o $@ $^

p106_2: p106_2.c
	$(CC) -Wall -o $@ $^

p107: p107.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
