// Generated by CoffeeScript 1.4.0
(function() {
  var fill;

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "Finling the " + container + " with " + liquid + "...";
  };

  alert(fill("cup"));

}).call(this);
