CC = gcc

PROGRAMS = 24-01 24-02 24-03 24-04 24-05 24-06 24-07 24-08 24-09 24-10 24-11

all: $(PROGRAMS)

24-01: 24-01.c
	$(CC) -Wall -o $@ $^

24-02: 24-02.c
	$(CC) -Wall -o $@ $^

24-03: 24-03.c
	$(CC) -Wall -o $@ $^

24-04: 24-04.c
	$(CC) -Wall -o $@ $^

24-05: 24-05.c
	$(CC) -Wall -o $@ $^

24-06: 24-06.c
	$(CC) -Wall -o $@ $^

24-07: 24-07.c
	$(CC) -Wall -o $@ $^

24-08: 24-08.c
	$(CC) -Wall -o $@ $^

24-09: 24-09.c
	$(CC) -Wall -o $@ $^

24-10: 24-10.c
	$(CC) -Wall -o $@ $^

24-11: 24-11.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
