// Generated by CoffeeScript 1.4.0
(function() {
  var favourite_color, question;

  favourite_color = "Blue. No, yel...";

  question = "Bridgekeeper: What... is your favourite color?            Galajad: " + favourite_color + "	    Bridgekeeper: Wrong!	    ";

}).call(this);
