CC = gcc

PROGRAMS = exam_29_1 exam_29_2 exam_29-2_1 exam_29-2_2 exam_29-3_1 exam_29-3_2 \
	   29-01 29-02 29-03 29-04 29-05 29-06 29-07 29-08 29-09 29-10 \
	   29-11 29-12 29-13 29-14 29-15 29-16 29-17

all: $(PROGRAMS)

exam_29_1: exam_29_1.c
	$(CC) -Wall -o $@ $^

exam_29_2: exam_29_2.c
	$(CC) -Wall -o $@ $^

exam_29-2_1: exam_29-2_1.c
	$(CC) -Wall -o $@ $^

exam_29-2_2: exam_29-2_2.c
	$(CC) -Wall -o $@ $^

exam_29-3_1: exam_29-3_1.c
	$(CC) -Wall -o $@ $^

exam_29-3_2: exam_29-3_2.c
	$(CC) -Wall -o $@ $^

29-01: 29-01.c
	$(CC) -Wall -o $@ $^

29-02: 29-02.c
	$(CC) -Wall -o $@ $^

29-03: 29-03.c
	$(CC) -Wall -o $@ $^

29-04: 29-04.c
	$(CC) -Wall -o $@ $^

29-05: 29-05.c
	$(CC) -Wall -o $@ $^

29-06: 29-06.c
	$(CC) -Wall -o $@ $^

29-07: 29-07.c
	$(CC) -Wall -o $@ $^

29-08: 29-08.c
	$(CC) -Wall -o $@ $^

29-09: 29-09.c
	$(CC) -Wall -o $@ $^

29-10: 29-10.c
	$(CC) -Wall -o $@ $^

29-11: 29-11.c
	$(CC) -Wall -o $@ $^

29-12: 29-12.c
	$(CC) -Wall -o $@ $^

29-13: 29-13.c
	$(CC) -Wall -o $@ $^

29-14: 29-14.c
	$(CC) -Wall -o $@ $^

29-15: 29-15.c
	$(CC) -Wall -o $@ $^

29-16: 29-16.c
	$(CC) -Wall -o $@ $^

29-17: 29-17.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
