CC = gcc

PROGRAMS = exam-30-1-1 exam-30-1-2 exam30-2\
	   30-01 30-02 30-03 30-04 30-05 30-06 30-07 30-08 30-09 30-10 \
	   30-11 30-12 30-13 30-14 30-15 30-16 30-17 30-18
all : $(PROGRAMS)

exam-30-1-1: exam-30-1-1.c
	$(CC) -Wall -o $@ $^

exam-30-1-2: exam-30-1-2.c
	$(CC) -Wall -o $@ $^

exam30-2: exam30-2.c
	$(CC) -Wall -o $@ $^

30-01: 30-01.c
	$(CC) -Wall -o $@ $^

30-02: 30-02.c
	$(CC) -Wall -o $@ $^

30-03: 30-03.c
	$(CC) -Wall -o $@ $^

30-04: 30-04.c
	$(CC) -Wall -o $@ $^

30-05: 30-05.c
	$(CC) -Wall -o $@ $^

30-06: 30-06.c
	$(CC) -Wall -o $@ $^

30-07: 30-07.c
	$(CC) -Wall -o $@ $^

30-08: 30-08.c
	$(CC) -Wall -o $@ $^

30-09: 30-09.c
	$(CC) -Wall -o $@ $^

30-10: 30-10.c
	$(CC) -Wall -o $@ $^

30-11: 30-11.c
	$(CC) -Wall -o $@ $^

30-12: 30-12.c
	$(CC) -Wall -o $@ $^

30-13: 30-13.c
	$(CC) -Wall -o $@ $^

30-14: 30-14.c
	$(CC) -Wall -o $@ $^

30-15: 30-15.c
	$(CC) -Wall -o $@ $^

30-16: 30-16.c
	$(CC) -Wall -o $@ $^

30-17: 30-17.c
	$(CC) -Wall -o $@ $^

30-18: 30-18.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
