// Generated by CoffeeScript 1.4.0
(function() {
  var ary, i;

  ary = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 10; i = ++_i) {
      _results.push(i * i);
    }
    return _results;
  })();

}).call(this);
