// Generated by CoffeeScript 1.4.0
(function() {
  var words,
    __indexOf = [].indexOf
    || function(item) {
		for (var i = 0, l = this.length; i < l; i++) {
			if (i in this && this[i] === item)
				return i;
		}
		return -1;
	};

  words = ["rattled", "roudy", "rebbles", "ranks"];

  if (__indexOf.call(words, "ranks") >= 0) {
    alert("Stop wagging me");
  }

}).call(this);
