// Generated by CoffeeScript 1.4.0
(function() {
  var trigger,
    __slice = [].slice;

  trigger = function() {
    var events;
    events = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    events.splice(1, 0, this);
    return this.constructor.trigger.apply(events);
  };

}).call(this);
