// Generated by CoffeeScript 1.4.0
(function() {
  var minstrel, num;

  num = 6;

  minstrel = (function() {
    var _results;
    _results = [];
    while (num -= 1) {
      _results.push(num + " Brave Sir Robin ran away");
    }
    return _results;
  })();

}).call(this);
