// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var callback;
    callback = function() {
      var val;
      val = $('select > option:selected').val();
      return alert(value);
    };
    setTimeout(callback);
    return 1000;
  });

}).call(this);
