// Generated by CoffeeScript 1.4.0
(function() {
  var object1, object2, object3;

  object1 = {
    one: 1,
    two: 2
  };

  object2 = {
    one: 1,
    two: 2
  };

  object3 = {
    one: 1,
    two: 2
  };

  User.create({
    name: "John Smith"
  });

}).call(this);
