CC = gcc

PROGRAMS = 26-1 26-2 26-3 26-4 26-5 26-6 26-7

all: $(PROGRAMS)

26-1: 26-1.c
	$(CC) -Wall -o $@ $^

26-2: 26-2.c
	$(CC) -Wall -o $@ $^

26-3: 26-3.c
	$(CC) -Wall -o $@ $^

26-4: 26-4.c
	$(CC) -Wall -o $@ $^

26-5: 26-5.c
	$(CC) -Wall -o $@ $^

26-6: 26-6.c
	$(CC) -Wall -o $@ $^

26-7: 26-7.c
	$(CC) -Wall -o $@ $^

clean:
	rm -rf $(PROGRAMS)
