// Generated by CoffeeScript 1.4.0
(function() {
  var i, name, _i, _len, _ref;

  _ref = ["Roger the pickpocket", "Roderick the robber"];
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    name = _ref[i];
    laert("" + i + " - Release " + name);
  }

}).call(this);
