// Generated by CoffeeScript 1.4.0
(function() {
  var first, last, names;

  names = {
    sam: seaborn,
    doona: moss
  };

  for (first in names) {
    last = names[first];
    alert("" + first + " ${last}");
  }

}).call(this);
