// Generated by CoffeeScript 1.4.0
(function() {
  var prisoner, _i, _len, _ref;

  _ref = ["Roger", "Roderick", "Brian"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    prisoner = _ref[_i];
    release(prisoner);
  }

}).call(this);
