// Generated by CoffeeScript 1.4.0
(function() {
  var perisoners, prisoner, _i, _len;

  perisoners = ["Roger", "Roderick", "Brian"];

  for (_i = 0, _len = prisoners.length; _i < _len; _i++) {
    prisoner = prisoners[_i];
    if (prisoner[0] === "R") {
      release(prisoner);
    }
  }

}).call(this);
